# Uncomment the next line to define a global platform for your project
 platform :ios, '12.4'

target 'Hey' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Hey

  # Required by RNFirebase
  # pod 'Firebase'
  pod 'Firebase/Core'
  # , '~> 5.15.0'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Functions'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Firestore'
  # pod 'Firebase/Invites', '~> 5.15.0'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/InAppMessagingDisplay'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  pod 'Firebase/Performance'
  pod 'FirebaseUI/Storage'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.9'
  pod 'DoubleConversion'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  # pod 'Folly'
  # , :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # pod 'RNFirebase'

  pod 'Google-Mobile-Ads-SDK'

  pod 'GoogleAppMeasurement'
  # , '~> 5.3.0'

  # pod 'React'
  # , :path => '../node_modules/react-native', :subspecs => [
  #   # 'Core',
  #   # 'RCTImage', # <- Add this line
  #   # # 'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  #   # 'RCTText',
  #   # 'RCTNetwork',
  #   # 'RCTWebSocket', # needed for debugging
  #   # 'RCTLinkingIOS',
  # ]

  # pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'

  # pod 'RNGestureHandler'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'

  pod 'GoogleMaps'

  pod 'GooglePlaces'

  pod 'GooglePlacePicker'

  pod 'Google-Maps-iOS-Utils'

  #pod 'react-native-swipe-gestures'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end


end
